services:
    sarayetel_web:
        build: .
        container_name: sarayetel
        ports:
            - "80:80"
        depends_on:
            - sarayetel_database
    sarayetel_database:
        image: "postgres:latest"
        container_name: sarayetel_postgres_server
        restart: "always"
        environment:
          POSTGRES_PASSWORD: "sarayetel_db_password"

volumes:
  sarayetel_data:            